name: CI Pipeline  # Nome del workflow

on:  # Evento che attiva il workflow
  push:  # Attiva il workflow quando c'è un push
    branches:
      - main  # Solo sul branch "main"
  pull_request:  # Attiva il workflow quando c'è una pull request
    branches:
      - main  # Solo sul branch "main"

jobs:
  build:
    runs-on: ubuntu-latest  # Specifica il sistema operativo

    steps:
      - name: Checkout code  # Primo step per ottenere il codice
        uses: actions/checkout@v2

      - name: Set up Python  # Step per configurare Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies  # Step per installare le dipendenze
        run: pip install -r requirements.txt

      - name: Run tests  # Step per eseguire i test
        run: pytest
